/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "Crd-End/pkg/apis/front/v1"
	scheme "Crd-End/pkg/client/clientset/versioned/scheme"
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FrontsGetter has a method to return a FrontInterface.
// A group's client should implement this interface.
type FrontsGetter interface {
	Fronts(namespace string) FrontInterface
}

// FrontInterface has methods to work with Front resources.
type FrontInterface interface {
	Create(ctx context.Context, front *v1.Front, opts metav1.CreateOptions) (*v1.Front, error)
	Update(ctx context.Context, front *v1.Front, opts metav1.UpdateOptions) (*v1.Front, error)
	UpdateStatus(ctx context.Context, front *v1.Front, opts metav1.UpdateOptions) (*v1.Front, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Front, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FrontList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Front, err error)
	FrontExpansion
}

// fronts implements FrontInterface
type fronts struct {
	client rest.Interface
	ns     string
}

// newFronts returns a Fronts
func newFronts(c *FrontV1Client, namespace string) *fronts {
	return &fronts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the front, and returns the corresponding front object, and an error if there is any.
func (c *fronts) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Front, err error) {
	result = &v1.Front{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fronts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Fronts that match those selectors.
func (c *fronts) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FrontList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FrontList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fronts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fronts.
func (c *fronts) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fronts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a front and creates it.  Returns the server's representation of the front, and an error, if there is any.
func (c *fronts) Create(ctx context.Context, front *v1.Front, opts metav1.CreateOptions) (result *v1.Front, err error) {
	result = &v1.Front{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fronts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(front).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a front and updates it. Returns the server's representation of the front, and an error, if there is any.
func (c *fronts) Update(ctx context.Context, front *v1.Front, opts metav1.UpdateOptions) (result *v1.Front, err error) {
	result = &v1.Front{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fronts").
		Name(front.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(front).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *fronts) UpdateStatus(ctx context.Context, front *v1.Front, opts metav1.UpdateOptions) (result *v1.Front, err error) {
	result = &v1.Front{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fronts").
		Name(front.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(front).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the front and deletes it. Returns an error if one occurs.
func (c *fronts) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fronts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fronts) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fronts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched front.
func (c *fronts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Front, err error) {
	result = &v1.Front{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fronts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
