/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	frontv1 "Crd-End/pkg/apis/front/v1"
	versioned "Crd-End/pkg/client/clientset/versioned"
	internalinterfaces "Crd-End/pkg/client/informers/externalversions/internalinterfaces"
	v1 "Crd-End/pkg/client/listers/front/v1"
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FrontInformer provides access to a shared informer and lister for
// Fronts.
type FrontInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.FrontLister
}

type frontInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFrontInformer constructs a new informer for Front type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFrontInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFrontInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFrontInformer constructs a new informer for Front type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFrontInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FrontV1().Fronts(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FrontV1().Fronts(namespace).Watch(context.TODO(), options)
			},
		},
		&frontv1.Front{},
		resyncPeriod,
		indexers,
	)
}

func (f *frontInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFrontInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *frontInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&frontv1.Front{}, f.defaultInformer)
}

func (f *frontInformer) Lister() v1.FrontLister {
	return v1.NewFrontLister(f.Informer().GetIndexer())
}
